### PR TITLE
Better formatting

### PR DESCRIPTION
**Pull request by fire**
Please review. I did this quick and dirty.

You are welcome to match the license if you want to rewrite the pr.

### CODE REVIEW

**Comment by Kubulambula** [comment]
Some files were deleted and in some places the formatting was even uglier while in others it was missed.

If you have nothing to add, I think that now it looks nice and neat. Thanks!

Closes https://github.com/Kubulambula/Godot-GDShell/issues/9

**Comment by fire** [comment]
Feel free to merge or modify as needed. Trying to release godot engine 4 so I'm a bit distracted.

**Comment by Kubulambula** [comment]
> Feel free to merge or modify as needed. Trying to release godot engine 4 so I'm a bit distracted.

Understandable

**Comment by Kubulambula** [comment]
Thanks! ❤️

**Pull request merged**
